Obrigado por contribuir para o nosso conteúdo localizado!

Todas as contribuições para o nosso conteúdo têm de aderir às seguintes diretrizes:

1. [Guia de Estilo de Idiomas da Microsoft](https://www.microsoft.com/Language/StyleGuides), que explica a intenção do texto quando se traduz do inglês para outro idioma.

2. [Portal de Idiomas da Microsoft](https://www.microsoft.com/language), que fornece os **termos**   relacionados com tecnologia em inglês e as traduções correspondentes utilizadas nos produtos Microsoft.

Quando aderir à nossa Comunidade de Localização em crescente expansão, poderá aprender mais sobre o Programa da Comunidade de Localização e sobre outras formas de poder   contribuir para o nosso programa ao visitar o [Wiki da Comunidade de Localização](https://github.com/Microsoft/Localization/wiki). Também partilhamos o processo de aprovação de PR nesta página, bem como algumas sugestões de <Gestão de PR>.
Continue a contribuir e atinja escalões mais elevados nas fileiras da nossa [Classificação dos   Contribuidores](https://microsoftl10n.github.io/) ao ser premiado com pontos   pelas suas contribuições de <localização>!

Microsoft Developer Relationship International Group
